FROM rstudio/plumber

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev

# Copy files
WORKDIR /app
COPY install_packages.R .
COPY api.R .
COPY plumber.R .

# Install R packages
RUN Rscript install_packages.R

# Expose port
EXPOSE 8000

# Run the API
CMD ["Rscript", "plumber.R"]